name: Deploy to S3 & CloudFront (Unique Preview)

on:
  pull_request:
    types:
      - closed

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          npm install  # Adjust based on your project

      - name: Build Project
        run: |
          npm run build  # Adjust based on your project

      - name: Generate Unique Deployment ID
        run: echo "DEPLOY_ID=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      - name: Deploy to S3 (Versioned Path)
        run: |
          aws s3 sync ./dist s3://$S3_BUCKET/previews/$DEPLOY_ID/ --delete

        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-east-1"
          S3_BUCKET: "your-s3-bucket-name"

      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/previews/$DEPLOY_ID/*"

        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DISTRIBUTION_ID: "your-cloudfront-distribution-id"

      - name: Output Preview URL
        run: |
          echo "Preview URL: https://your-cloudfront-domain.com/previews/$DEPLOY_ID/index.html"
